"""Added image to Members database

Revision ID: 5b47dd68659c
Revises: e7aa71b56b9f
Create Date: 2022-04-10 00:00:00.081652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b47dd68659c'
down_revision = 'e7aa71b56b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('image', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'image')
    # ### end Alembic commands ###
