"""testing out selectfield

Revision ID: 6058de6fb471
Revises: c40b01113d95
Create Date: 2022-04-11 06:04:42.401444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6058de6fb471'
down_revision = 'c40b01113d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('gender', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'gender')
    # ### end Alembic commands ###
