"""Testing out Image store and display

Revision ID: 63d31b4d3e7d
Revises: dfe5070151da
Create Date: 2022-04-11 10:21:38.935798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d31b4d3e7d'
down_revision = 'dfe5070151da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('country', sa.String(length=100), nullable=False))
    op.add_column('members', sa.Column('image_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'image_name')
    op.drop_column('members', 'country')
    # ### end Alembic commands ###
