"""testing out datefield

Revision ID: 8d8ba25bf0cf
Revises: 6058de6fb471
Create Date: 2022-04-11 06:19:27.094787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8ba25bf0cf'
down_revision = '6058de6fb471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('birth_date', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'birth_date')
    # ### end Alembic commands ###
