"""Changed the image filename

Revision ID: c40b01113d95
Revises: 5b47dd68659c
Create Date: 2022-04-10 00:26:39.000787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c40b01113d95'
down_revision = '5b47dd68659c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'filename')
    op.drop_column('members', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('data', sa.BLOB(), nullable=True))
    op.add_column('members', sa.Column('filename', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
