"""tweaking image upload

Revision ID: ca48f578b319
Revises: 63d31b4d3e7d
Create Date: 2022-04-11 10:41:15.581039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca48f578b319'
down_revision = '63d31b4d3e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('image_data', sa.LargeBinary(), nullable=False))
    op.add_column('members', sa.Column('render_data', sa.Text(), nullable=False))
    op.drop_column('members', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('image', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('members', 'render_data')
    op.drop_column('members', 'image_data')
    # ### end Alembic commands ###
