"""testing out TelField

Revision ID: dfe5070151da
Revises: 8d8ba25bf0cf
Create Date: 2022-04-11 08:00:15.322999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe5070151da'
down_revision = '8d8ba25bf0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('phone', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'phone')
    # ### end Alembic commands ###
