"""added title to members form

Revision ID: e7aa71b56b9f
Revises: c9bf543e5769
Create Date: 2022-04-09 23:01:42.224033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7aa71b56b9f'
down_revision = 'c9bf543e5769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('title', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'title')
    # ### end Alembic commands ###
