"""empty message

Revision ID: f6766021dbf6
Revises: f8d7c7cf1e69
Create Date: 2022-04-09 09:44:35.279267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6766021dbf6'
down_revision = 'f8d7c7cf1e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_members', sa.Column('username', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_members', 'username')
    # ### end Alembic commands ###
