"""Added others to the form

Revision ID: fbe8893d9120
Revises: ca48f578b319
Create Date: 2022-04-11 16:24:01.234092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe8893d9120'
down_revision = 'ca48f578b319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('others', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'others')
    # ### end Alembic commands ###
